export const dataKota = [
  {value: 'Aceh Besar', key: '1'},
  {value: 'Banda Aceh', key: '2'},
  {value: 'Bandar Lampung', key: '3'},
  {value: 'Bandung', key: '4'},
  {value: 'Banjar', key: '5'},
  {value: 'Banyumas', key: '6'},
  {value: 'Banyuwangi', key: '7'},
  {value: 'Batu Islands', key: '8'},
  {value: 'Bekasi', key: '9'},
  {value: 'Bengkalis', key: '10'},
  {value: 'Binjai', key: '11'},
  {value: 'Bireuen', key: '12'},
  {value: 'Bitung', key: '13'},
  {value: 'Blitar', key: '14'},
  {value: 'Blora', key: '15'},
  {value: 'Bogor', key: '16'},
  {value: 'Bondowoso', key: '17'},
  {value: 'Bojonegoro', key: '18'},
  {value: 'Boyolali', key: '19'},
  {value: 'Brebes', key: '20'},
  {value: 'Bukittinggi', key: '21'},
  {value: 'Bulukumba', key: '22'},
  {value: 'Ciamis', key: '23'},
  {value: 'Cianjur', key: '24'},
  {value: 'Cilacap', key: '25'},
  {value: 'Cilegon', key: '26'},
  {value: 'Cimahi', key: '27'},
  {value: 'Cirebon', key: '28'},
  {value: 'Demak', key: '29'},
  {value: 'Denpasar', key: '30'},
  {value: 'Denpasar', key: '30'},
  {value: 'Depok', key: '31'},
  {value: 'Dumai', key: '32'},
  {value: 'Ende', key: '33'},
  {value: 'Gorontalo', key: '34'},
  {value: 'Gresik', key: '35'},
  {value: 'Indramayu', key: '36'},
  {value: 'Jakarta Barat', key: '37'},
  {value: 'Jakarta Pusat', key: '38'},
  {value: 'Jakarta Selatan', key: '39'},
  {value: 'Jakarta Timur', key: '40'},
  {value: 'Jakarta Utara', key: '41'},
  {value: 'Jambi', key: '42'},
  {value: 'Jayapura', key: '43'},
  {value: 'Jember', key: '44'},
  {value: 'Jepara', key: '45'},
  {value: 'Jombang', key: '46'},
  {value: 'Kabanjahe', key: '47'},
  {value: 'Kediri', key: '48'},
  {value: 'Kendari', key: '49'},
  {value: 'Kota Sorong', key: '50'},
  {value: 'Kotamobagu', key: '51'},
  {value: 'Kudus', key: '52'},
  {value: 'Kuningan', key: '53'},
  {value: 'Kupang', key: '54'},
  {value: 'Kutacane', key: '55'},
  {value: 'Lahat', key: '56'},
  {value: 'Lamongan', key: '57'},
  {value: 'Lampung', key: '58'},
  {value: 'Langsa', key: '59'},
  {value: 'Lubuklinggau', key: '60'},
  {value: 'Lumajang', key: '61'},
  {value: 'Luwuk', key: '62'},
  {value: 'Madiun', key: '63'},
  {value: 'Magelang', key: '64'},
  {value: 'Majalengka', key: '65'},
  {value: 'Makassar', key: '66'},
  {value: 'Malang', key: '67'},
  {value: 'Malinau', key: '68'},
  {value: 'Manado', key: '69'},
  {value: 'Manokwari', key: '70'},
  {value: 'Martapura', key: '71'},
  {value: 'Masohi', key: '72'},
  {value: 'Mataram', key: '73'},
  {value: 'Maumere', key: '74'},
  {value: 'Medan', key: '75'},
  {value: 'Melawi', key: '76'},
  {value: 'Metro', key: '77'},
  {value: 'Mojokerto', key: '78'},
  {value: 'Muara Enim', key: '79'},
  {value: 'Muara Teweh', key: '80'},
  {value: 'Muntok', key: '81'},
  {value: 'Nabire', key: '82'},
  {value: 'Nagan Raya', key: '83'},
  {value: 'Nunukan', key: '84'},
  {value: 'Pacitan', key: '85'},
  {value: 'Padang', key: '86'},
  {value: 'Padang Panjang', key: '87'},
  {value: 'Padangsidempuan', key: '88'},
  {value: 'Pagar Alam', key: '89'},
  {value: 'Palangka Raya', key: '90'},
  {value: 'Palembang', key: '91'},
  {value: 'Palopo', key: '92'},
  {value: 'Palu', key: '93'},
  {value: 'Pamekasan', key: '94'},
  {value: 'Pandeglang', key: '95'},
  {value: 'Pangkajene Dan Kepulauan', key: '96'},
  {value: 'Pangkal Pinang', key: '97'},
  {value: 'Panyabungan', key: '98'},
  {value: 'Parepare', key: '99'},
  {value: 'Pariaman', key: '100'},
  {value: 'Pasarwajo', key: '101'},
  {value: 'Pasuruan', key: '102'},
  {value: 'Pati', key: '103'},
  {value: 'Payakumbuh', key: '104'},
  {value: 'Pekalongan', key: '105'},
  {value: 'Pekanbaru', key: '106'},
  {value: 'Pelaihari', key: '107'},
  {value: 'Pematangsiantar', key: '108'},
  {value: 'Penajam Paser Utara', key: '109'},
  {value: 'Pendopo', key: '110'},
  {value: 'Pinrang', key: '111'},
  {value: 'Polewali Mandar', key: '112'},
  {value: 'Ponorogo', key: '113'},
  {value: 'Pontianak', key: '114'},
  {value: 'Prabumulih', key: '115'},
  {value: 'Praya', key: '116'},
  {value: 'Probolinggo', key: '117'},
  {value: 'Purwakarta', key: '118'},
  {value: 'Purwodadi', key: '119'},
  {value: 'Purwokerto', key: '120'},
  {value: 'Purworejo', key: '121'},
  {value: 'Raha', key: '122'},
  {value: 'Rangkasbitung', key: '123'},
  {value: 'Rantau', key: '124'},
  {value: 'Rantepao', key: '125'},
  {value: 'Rembang', key: '126'},
  {value: 'Ruteng', key: '127'},
  {value: 'Sabang', key: '128'},
  {value: 'Salatiga', key: '129'},
  {value: 'Samarinda', key: '130'},
  {value: 'Sambas', key: '131'},
  {value: 'Sampang', key: '132'},
  {value: 'Sangatta', key: '133'},
  {value: 'Sarolangun', key: '134'},
  {value: 'Sawah Lunto', key: '135'},
  {value: 'Semarang', key: '136'},
  {value: 'Serang', key: '137'},
  {value: 'Serdang Bedagai', key: '138'},
  {value: 'Serui', key: '139'},
  {value: 'Sidikalang', key: '140'},
  {value: 'Sidoarjo', key: '141'},
  {value: 'Sigli', key: '142'},
  {value: 'Sijunjung', key: '143'},
  {value: 'Simpang Empat', key: '144'},
  {value: 'Singaparna', key: '145'},
  {value: 'Singaraja', key: '146'},
  {value: 'Singkawang', key: '147'},
  {value: 'Sinjai', key: '148'},
  {value: 'Situbondo', key: '149'},
  {value: 'Slawi', key: '150'},
  {value: 'Sleman', key: '151'},
  {value: 'Soe', key: '152'},
  {value: 'Solok', key: '153'},
  {value: 'Sorong', key: '154'},
  {value: 'Sragen', key: '155'},
  {value: 'Subang', key: '156'},
  {value: 'Subulussalam', key: '157'},
  {value: 'Sukabumi', key: '158'},
  {value: 'Sukoharjo', key: '159'},
  {value: 'Sumbawa Besar', key: '160'},
  {value: 'Sumbawa', key: '161'},
  {value: 'Sumbawa Barat', key: '162'},
  {value: 'Sumedang', key: '163'},
  {value: 'Sumenep', key: '164'},
  {value: 'Sungaipenuh', key: '165'},
  {value: 'Sungailiat', key: '166'},
  {value: 'Sungai Liat', key: '167'},
  {value: 'Sungguminasa', key: '168'},
  {value: 'Surabaya', key: '169'},
  {value: 'Surakarta', key: '170'},
  {value: 'Tahuna', key: '171'},
  {value: 'Takalar', key: '172'},
  {value: 'Taliabu', key: '173'},
  {value: 'Tamiang Layang', key: '174'},
  {value: 'Tangerang', key: '175'},
  {value: 'Tanjung Balai', key: '176'},
  {value: 'Tanjung Enim', key: '177'},
  {value: 'Tanjung Pandan', key: '178'},
  {value: 'Tanjung Pinang', key: '179'},
  {value: 'Tanjung Redeb', key: '180'},
  {value: 'Tanjung Selor', key: '181'},
  {value: 'Tapak Tuan', key: '182'},
  {value: 'Tarakan', key: '183'},
  {value: 'Tarutung', key: '184'},
  {value: 'Tasikmalaya', key: '185'},
  {value: 'Tebing Tinggi', key: '186'},
  {value: 'Tegal', key: '187'},
  {value: 'Teluk Bintuni', key: '188'},
  {value: 'Teluk Kuantan', key: '189'},
  {value: 'Temanggung', key: '190'},
  {value: 'Ternate', key: '191'},
  {value: 'Tidore', key: '192'},
  {value: 'Tigaraksa', key: '193'},
  {value: 'Toboali', key: '194'},
  {value: 'Tolitoli', key: '195'},
  {value: 'Tomohon', key: '196'},
  {value: 'Tondano', key: '197'},
  {value: 'Trenggalek', key: '198'},
  {value: 'Tual', key: '199'},
  {value: 'Tuban', key: '200'},
];

export const dataNull = [
  {
    value: '',
    key: '',
  },
];
