export const dataProvinsi = [
  {value: 'Aceh', key: '1'},
  {value: 'Sumatera Utara', key: '2'},
  {value: 'Sumatera Barat', key: '3'},
  {value: 'Riau', key: '4'},
  {value: 'Kepulauan Riau', key: '5'},
  {value: 'Jambi', key: '6'},
  {value: 'Sumatera Selatan', key: '7'},
  {value: 'Bangka Belitung', key: '8'},
  {value: 'Bengkulu', key: '9'},
  {value: 'Lampung', key: '10'},
  {value: 'Banten', key: '11'},
  {value: 'DKI Jakarta', key: '12'},
  {value: 'Jawa Barat', key: '13'},
  {value: 'Jawa Tengah', key: '14'},
  {value: 'DI Yogyakarta', key: '15'},
  {value: 'Jawa Timur', key: '16'},
  {value: 'Bali', key: '17'},
  {value: 'Nusa Tenggara Barat', key: '18'},
  {value: 'Nusa Tenggara Timur', key: '19'},
  {value: 'Kalimantan Barat', key: '20'},
  {value: 'Kalimantan Tengah', key: '21'},
  {value: 'Kalimantan Selatan', key: '22'},
  {value: 'Kalimantan Timur', key: '23'},
  {value: 'Kalimantan Utara', key: '24'},
  {value: 'Sulawesi Utara', key: '25'},
  {value: 'Gorontalo', key: '26'},
  {value: 'Sulawesi Tengah', key: '27'},
  {value: 'Sulawesi Barat', key: '28'},
  {value: 'Sulawesi Selatan', key: '29'},
  {value: 'Sulawesi Tenggara', key: '30'},
  {value: 'Maluku', key: '31'},
  {value: 'Maluku Utara', key: '32'},
  {value: 'Papua Barat', key: '33'},
  {value: 'Papua', key: '34'},
];
